[tool.black]
line-lenght = 88
target-version = ['py311']

#  Flake config
[tool.isort]
profile = 'black'

#  Isort config
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_lenght = 88

#  Autoflake config
[tool.autoflake]
check_diff = true
#  imports = ['sqlalchemy']

#  PyRight config(аналог mypy)
[tool.pyright]
include = []





