"""add field check position

Revision ID: 20081653d05e
Revises: 1cde354dcffb
Create Date: 2024-04-04 17:57:11.563483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20081653d05e'
down_revision: Union[str, None] = '1cde354dcffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions_check', sa.Column('price_min_in_cash_receipt', sa.Integer(), nullable=True))
    op.add_column('positions_check', sa.Column('price_max_in_cash_receipt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions_check', 'price_max_in_cash_receipt')
    op.drop_column('positions_check', 'price_min_in_cash_receipt')
    # ### end Alembic commands ###
