"""[upd] cash_shift model

Revision ID: 3e792b221e14
Revises: 5e205c94c2c9
Create Date: 2023-08-30 14:04:21.186112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e792b221e14"
down_revision = "5e205c94c2c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cash_shifts", sa.Column("hide", sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, "events", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "events", type_="unique")
    op.drop_column("cash_shifts", "hide")
    # ### end Alembic commands ###
