"""add field position check price_may_change_in_cash_receipt

Revision ID: 4c46c21e4d85
Revises: a193df8365ba
Create Date: 2024-05-31 11:22:12.706576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c46c21e4d85'
down_revision: Union[str, None] = 'a193df8365ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions_check', sa.Column('price_may_change_in_cash_receipt', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions_check', 'price_may_change_in_cash_receipt')
    # ### end Alembic commands ###
