"""added field closed date

Revision ID: 536d1eb5dd8d
Revises: 4c46c21e4d85
Create Date: 2024-06-21 14:55:42.371486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536d1eb5dd8d'
down_revision: Union[str, None] = '4c46c21e4d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_shifts', sa.Column('closed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_shifts', 'closed_date')
    # ### end Alembic commands ###
