"""[upd]

Revision ID: 55863f778d75
Revises: 71d217a13da8
Create Date: 2023-08-31 15:13:57.694436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55863f778d75"
down_revision = "71d217a13da8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
