"""[upd] cash_shift model

Revision ID: 5e205c94c2c9
Revises: f85c15190003
Create Date: 2023-08-30 11:03:29.373215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e205c94c2c9"
down_revision = "f85c15190003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("queue", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("send_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_unique_constraint(None, "cash_shifts", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cash_shifts", type_="unique")
    op.drop_table("events")
    # ### end Alembic commands ###
