"""[upd]

Revision ID: 71d217a13da8
Revises: 8caae85338bc
Create Date: 2023-08-31 15:12:53.399765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71d217a13da8"
down_revision = "8caae85338bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "positions_check_check_id_fkey", "positions_check", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "positions_check", "checks", ["check_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "positions_check", type_="foreignkey")
    op.create_foreign_key(
        "positions_check_check_id_fkey",
        "positions_check",
        "checks",
        ["check_id"],
        ["id"],
    )
    # ### end Alembic commands ###
