"""add number and fix cash register

Revision ID: 77e8fcdd098f
Revises: e5c253793e66
Create Date: 2024-03-15 11:51:39.006494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e8fcdd098f'
down_revision: Union[str, None] = 'e5c253793e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_shifts', sa.Column('number', sa.Integer(), nullable=True))
    op.alter_column('cash_shifts', 'cash_registr_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_shifts', 'cash_registr_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('cash_shifts', 'number')
    # ### end Alembic commands ###
