"""[upd] cash_shift model

Revision ID: 8caae85338bc
Revises: cc7dbbf13026
Create Date: 2023-08-30 16:53:40.190096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8caae85338bc"
down_revision = "cc7dbbf13026"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cash_shifts", sa.Column("store_id", sa.Integer(), nullable=False))
    op.add_column(
        "cash_shifts", sa.Column("workplace_id", sa.Integer(), nullable=False)
    )
    op.add_column("cash_shifts", sa.Column("personal_id", sa.Integer(), nullable=False))
    op.add_column(
        "cash_shifts", sa.Column("cash_registr_id", sa.Integer(), nullable=False)
    )
    op.drop_column("cash_shifts", "worker_id")
    op.drop_column("cash_shifts", "device_id")
    op.drop_column("cash_shifts", "rmk_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cash_shifts",
        sa.Column("rmk_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "cash_shifts",
        sa.Column("device_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "cash_shifts",
        sa.Column("worker_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("cash_shifts", "cash_registr_id")
    op.drop_column("cash_shifts", "personal_id")
    op.drop_column("cash_shifts", "workplace_id")
    op.drop_column("cash_shifts", "store_id")
    # ### end Alembic commands ###
