"""init

Revision ID: 953ca82740a0
Revises: 
Create Date: 2023-08-10 18:45:28.088640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953ca82740a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('rmk_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('check_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_taxation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_shift_id', sa.Integer(), nullable=False),
    sa.Column('type_operation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type_payment_id', sa.Integer(), nullable=False),
    sa.Column('number_fiscal_document', sa.Integer(), nullable=False),
    sa.Column('check_status_id', sa.Integer(), nullable=False),
    sa.Column('type_taxation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cash_shift_id'], ['cash_shift.id'], ),
    sa.ForeignKeyConstraint(['check_status_id'], ['check_status.id'], ),
    sa.ForeignKeyConstraint(['type_operation_id'], ['type_operation.id'], ),
    sa.ForeignKeyConstraint(['type_payment_id'], ['type_payment.id'], ),
    sa.ForeignKeyConstraint(['type_taxation_id'], ['type_taxation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['check.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_check')
    op.drop_table('check')
    op.drop_table('type_taxation')
    op.drop_table('type_payment')
    op.drop_table('type_operation')
    op.drop_table('check_status')
    op.drop_table('cash_shift')
    # ### end Alembic commands ###
