"""add field reasonCheckName

Revision ID: b1fc2cbcb335
Revises: fe40240e177a
Create Date: 2024-04-26 09:36:48.937198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fc2cbcb335'
down_revision: Union[str, None] = 'fe40240e177a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checks', sa.Column('reasonCheckName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checks', 'reasonCheckName')
    # ### end Alembic commands ###
