"""[add] check return reason

Revision ID: c7fed8b1d4d1
Revises: a1df07ac9851
Create Date: 2023-09-21 15:50:53.107502

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7fed8b1d4d1"
down_revision: Union[str, None] = "a1df07ac9851"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("checks", sa.Column("reason_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checks", "reason_id")
    # ### end Alembic commands ###
