"""[fix] relationships

Revision ID: cc7dbbf13026
Revises: 3e792b221e14
Create Date: 2023-08-30 14:45:44.967323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7dbbf13026'
down_revision = '3e792b221e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
