"""[upd] workerId

Revision ID: e5c253793e66
Revises: e6a9e8050024
Create Date: 2023-12-20 14:21:30.508022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5c253793e66"
down_revision: Union[str, None] = "e6a9e8050024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cash_shifts", "worker_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cash_shifts", "worker_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
