"""[upd] models

Revision ID: f85c15190003
Revises: 
Create Date: 2023-08-25 12:24:20.249550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f85c15190003"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_shifts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("rmk_id", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "check_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "types_operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "types_payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "types_taxation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("number_fiscal_document", sa.String(), nullable=False),
        sa.Column("cash_shift_id", sa.Integer(), nullable=False),
        sa.Column("type_operation_id", sa.Integer(), nullable=False),
        sa.Column("type_payment_id", sa.Integer(), nullable=False),
        sa.Column("check_status_id", sa.Integer(), nullable=False),
        sa.Column("type_taxation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cash_shift_id"],
            ["cash_shifts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["check_status_id"],
            ["check_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_operation_id"],
            ["types_operation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_payment_id"],
            ["types_payment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_taxation_id"],
            ["types_taxation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions_check",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("check_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["check_id"],
            ["checks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions_check")
    op.drop_table("checks")
    op.drop_table("types_taxation")
    op.drop_table("types_payment")
    op.drop_table("types_operation")
    op.drop_table("check_statuses")
    op.drop_table("cash_shifts")
    # ### end Alembic commands ###
