"""nullable true on number and fiscal number

Revision ID: fe40240e177a
Revises: 20081653d05e
Create Date: 2024-04-23 20:20:07.001401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe40240e177a'
down_revision: Union[str, None] = '20081653d05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checks', 'number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checks', 'number_fiscal_document',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checks', 'number_fiscal_document',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checks', 'number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
